cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://x.com/mir0mori
spring:
  application:
    name: curso-erudio
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/erudio?useTimeZone=true&serverTimeZone=UTC
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    com.miromorii.cursoerudio: INFO
springdoc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true